apiVersion: v2
name: sgbi
description: Un Helm Chart para desplegar Kafka, Spark y TimescaleDB.
type: application
version: 0.1.0
appVersion: 1.0.0
dependencies:
  - name: kafka
    version: "22.1.4"
    repository: "oci://registry-1.docker.io/bitnamicharts"
  - name: spark
    version: "9.3.5"
    repository: "oci://registry-1.docker.io/bitnamicharts"
  - name: timescaledb-single
    version: "0.33.1"
    repository: "https://charts.timescale.com/"
