# Usa una imagen oficial de Python como base
FROM python:3.10-slim

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app/scripts

# Copia los archivos de la aplicación al contenedor
COPY . .

# Expone el puerto 5000 para la API Flask
EXPOSE 5000
