apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-timescaledb
  namespace: {{ .Values.timescaledb.namespaceOverride }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      containers:
        - name: timescaledb
          image: {{ .Values.timescaledb.image.repository }}:{{ .Values.timescaledb.image.tag }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: mydb
            - name: POSTGRES_USER
              value: myuser
            - name: POSTGRES_PASSWORD
              value: mypassword
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-timescaledb
  namespace: {{ .Values.timescaledb.namespaceOverride }}
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: timescaledb
