apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-timescaledb
  namespace: {{ .Values.timescaledb.namespaceOverride }}
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: timescaledb
