---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: timescaledb-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/timescaledb-data  # Ruta en el nodo; asegúrate de que exista y tenga permisos
  storageClassName: "local-storage"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timescaledb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "local-storage"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescaledb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      containers:
      - name: timescaledb
        image: timescale/timescaledb:latest-pg14
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_DB
            value: "mydb"
          - name: POSTGRES_USER
            value: "myuser"
          - name: POSTGRES_PASSWORD
            value: "mypassword"
        volumeMounts:
          - name: timescaledb-data
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: timescaledb-data
          persistentVolumeClaim:
            claimName: timescaledb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: timescaledb
spec:
  selector:
    app: timescaledb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
